// Every page the client routes to (client/src/App.jsx), as the tracker
// normalizes it, so the Engagement tab can list the pages nobody opened.
// knownPages.test.js reads App.jsx and fails when this list falls behind it.
//
// Route parameters are written :id because that is what a concrete id
// normalizes to (routeNormalizer.js).

export const KNOWN_PAGES = Object.freeze([
  '/',
  '/accountability',
  '/admin-document-grading',
  '/admin/analytics',
  '/admin/assigned-interviews',
  '/admin/email-templates',
  '/admin/final-round-interview',
  '/admin/help',
  '/admin/interview-interface',
  '/admin/interview-scheduling',
  '/admin/interviews',
  '/admin/meeting-slots',
  '/admin/question-bank',
  '/admin/referrals',
  '/admin/release-notes',
  '/applicant-information',
  '/application-list',
  '/application/:id',
  '/applications',
  '/assigned-interviews',
  '/candidate-detail/:id',
  '/candidate-list',
  '/candidate-management',
  '/candidates',
  '/cases',
  '/cases/:id/tags',
  '/cycles',
  '/dashboard',
  '/document-grading',
  '/events',
  '/forgot-password',
  '/get-to-know-uc',
  '/help',
  '/interview-prep',
  '/interview-rsvp',
  '/interview-signup',
  '/interviews/:id',
  '/live-vote/:id',
  '/login',
  '/master-communications',
  '/meet',
  '/member-signup',
  '/member/final-round-interview',
  '/member/first-round-interview',
  '/member/interview-interface',
  '/member/meeting-slots',
  '/member/referrals',
  '/member/talent-network',
  '/onboarding',
  '/partner/resumes',
  '/privacy',
  '/profile',
  '/reset-password',
  '/review-teams',
  '/signup',
  '/staging',
  '/talent-pool',
  '/talent/profile',
  '/talent/signup',
  '/talent/verify',
  '/unsubscribe',
  '/user-management',
  '/verify-email',
]);

/** A route pattern from App.jsx as the tracker would record it. */
export const normalizeRoutePattern = (path) => path.replace(/:[A-Za-z]+/g, ':id');
